config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  devise_for :users
  resources :projects
  resources :contacts, only: [:index, :new, :create] do
    member do
      get 'sent'
    end
  end
  resources :homepages, only: [:edit, :update]
  resources :photos, only: [:destroy]
  resources :updates
  root to: 'pages#home'
  get "about", to: "pages#about", as: "about"
  get "bronze", to: "projects#bronze", as: "bronze"
  get "scrap", to: "projects#scrap", as: "scrap"
  get "news", to: "updates#index", as: "news"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/homepage.rb
class Homepage < ApplicationRecord
  belongs_to :project_one, class_name: "Project", optional: true
  belongs_to :project_two, class_name: "Project", optional: true
  belongs_to :project_three, class_name: "Project", optional: true
  belongs_to :project_four, class_name: "Project", optional: true
  has_rich_text :homepage_content
  has_rich_text :bronze_content
  has_rich_text :scrap_content
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :project
  mount_uploader :url, PhotoUploader
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/models/update.rb
class Update < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :sent]

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.sent = false
    @contact.save
    redirect_to new_contact_path
    flash[:notice] = "Thanks for your request, a brochure will be with you soon."
  end

  def sent
    @contact = Contact.find(params[:id])
    @contact.sent = true
    if @contact.save
      redirect_to contacts_path
    else
      flash[:error] = 'Something went wrong'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :id)
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController

  def edit
    @homepage = Homepage.find(params[:id])
  end

  def update
    @homepage = Homepage.find(params[:id])
    if @homepage.update(homepage_params)
      redirect_to root_path, notice: 'homepage was successfully updated.'
    else
      render :edit
    end
  end

  private

  def homepage_params
    params.require(:homepage).permit(:project_one_id, :project_two_id, :project_three_id, :project_four_id, :bronze_title, :bronze_content, :scrap_title, :scrap_content, :work_title)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about, :contact]

  def home
    @homepage = Homepage.first
    @projects = Project.where(featured: true).last(9).reverse
  end

  def about
  end

  def contact
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    @photo = Photo.find(params[:id])
    @project = Project.find(params[:project])
    @photo.destroy
    redirect_to project_path(@project)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :scrap, :bronze]
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def bronze
    @projects = Project.where(bronze: true).reverse
    @homepage = Homepage.first
  end

  def scrap
    @projects = Project.where(bronze: false).reverse
    @homepage = Homepage.first
  end

  def show
    @photos = @project.photos.select{ |photo| photo.url.url != nil }
    @photos.reverse!
  end

  def new
    @project = Project.new
    @photo = @project.photos.build
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    params[:project][:bronze] == "BRONZE" ? @project.bronze = true : @project.bronze = false
    if @project.save && params[:photos]
      params[:photos]['url'].each do |uri|
        @photo = @project.photos.create!(url: uri)
      end
      redirect_to project_path(@project)
    elsif @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @project.update(project_params)
    if @project.save
      if params[:photos]
        params[:photos]['url'].each do |uri|
          @project.photos.create!(url: uri)
        end
      end
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to :root
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:sub, :photo, :name, :description, :featured, :edition, :year, :dimensions, :finish, :price, photos_attributes: [:url, :id, :project_id])
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_update, only: [:show, :edit, :update, :destroy]

  def show
    @bg = random_etch
  end

  def index
    @updates = Update.last(10).reverse
    @bg = random_etch
  end

  def new
    @update = Update.new
  end

  def destroy
    if !current_user
      redirect_to :root
    else
      @update.destroy
      redirect_to updates_path
    end
  end

  def create
    if !current_user
      redirect_to :root
    else
      @update = Update.new(update_params)
      @update.title = @update.title.titleize
      if @update.save
        redirect_to updates_path
      else
        render :new
      end
    end
  end

  def edit
  end

  def update
    @update.update(update_params)
    if @update.save!
      redirect_to updates_path
    else
      render :edit
    end
  end

  private

  def random_etch
    etchs = ["e.png","w.png","ws.jpg","l.jpg"]
    etchs.sample
  end

  def find_update
    @update = Update.find(params[:id])
  end

  def update_params
    params.require(:update).permit(:title, :url, :link, :description, :photo, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contacts/index.html.erb
<h3 style="margin-bottom: 50px;margin-left: 40px;">Hey James, this page and the link to it are only available to you</h3>
<div class="container">
  <% @contacts.reverse.each do |contact| %>
    <% if !contact.sent %>
      <div class="email-cont">
        <%= mail_to contact.email do %>
          <p style="color:red;margin:0;margin-right: 20px;">
            <%= contact.email %> - Not Yet Emailed
          </p>
        <% end %>
        <%= link_to(sent_contact_path(contact)) do %>
          <div class="btn btn-primary">Sent</div>
        <% end %>
      </div>
    <% else %>
      <div class="email-cont">
        <p style="color:green;margin:0;margin-right: 20px;">
          <%= contact.email %> - Email Sent
        </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="contact-container">
  <div class="section">
    <div class="contact-flex-holder ">
      <div class="contact-holder">
        <h3 class="index-header mt20 black">CONTACT</h3>
        <p class="text-center black">Please get in contact by</p>
        <div class="contact-flex">
          <%= image_tag ("Mail.png"), class: "contact-avatar" %>
          <a class="bold-large black margin-left" style="font-family: 'Raleway'" href="mailto:jamie1wild@gmail.com">jamie1wild@gmail.com</a>
        </div>
        <div class="contact-flex">
          <%= image_tag ("Phone.png"), class: "contact-avatar" %>
          <p class="bold-large black margin-left">+44 7921 812332</p>
        </div>
        <a class="download" href="<%= asset_path('ONE_WILD.pdf') %>" download>
          Download Brochure
        </a>
      </div>
    </div>
  </div>
  <div class="section"></div>
</div>

app/views/homepages/edit.html.erb
<div class="container">
  <h1 class="tc p-3">Edit Pages</h1>
  <%= simple_form_for(@homepage) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <h3 class="mt-4">Homepage</h3>
    <h4>Top Carousel</h4>
    <div class="row">
      <div class="col-sm-12 inherit col-md-3">
        <div class="form-inputs">
          <%= f.association :project_one %>
        </div>
      </div>
      <div class="col-sm-12 inherit col-md-3">
        <div class="form-inputs">
          <%= f.association :project_two %>
        </div>
      </div>
      <div class="col-sm-12 inherit col-md-3">
        <div class="form-inputs">
          <%= f.association :project_three %>
        </div>
      </div>
      <div class="col-sm-12 inherit col-md-3">
        <div class="form-inputs">
          <%= f.association :project_four %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-inputs pl-4">
        <p>Blurb</p>
        <%= f.rich_text_area :homepage_content %>
        <p class="mt-3">Title for pictures</p>
        <%= f.input :work_title, label: false %>
      </div>
    </div>
    <hr>
    <h3 class="mt-4">Bronze</h3>
    <div class="row">
      <div class="form-inputs pl-4">
        <%= f.input :bronze_title, label: "Bronze title" %>
        <p>Blurb</p>
        <%= f.rich_text_area :bronze_content %>
      </div>
    </div>
    <hr>
    <h3 class="mt-4">Scrap</h3>
    <div class="row">
      <div class="form-inputs pl-4">
        <%= f.input :scrap_title, label: "Scrap title" %>
        <p>Blurb</p>
        <%= f.rich_text_area :scrap_content %>
      </div>
    </div>
    <div class="mb-4 mt-4 form-actions pv-mid">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-26844243-1');
    </script>
    <meta charset="UTF-8">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
    <title>James Wild Sculptures</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Antic|Open+Sans:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/butler" type="text/css"/>
    <link href="//db.onlinewebfonts.com/c/6afb442b0dac4242aa6c3e77985e119f?family=Orpheus" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= javascript_pack_tag 'application' %>
    <%= favicon_link_tag asset_path('Logo.jpg') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="main-body">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/projects/show.html.erb
<div class="show-container">
  <% if @project.bronze == true %>
    <h3 class="index-header" style="padding-bottom: 10px;font-family: 'ButlerSemiBold';letter-spacing: unset;"><%= @project&.sub&.upcase %></h3>
  <% end %>
  <h3 class="index-header" style="padding-bottom: 20px;letter-spacing: unset;font-size: 4rem;"><%= @project.name %></h3>
  <% if @project.bronze == true %>
    <p style="text-align:center; padding-bottom: 20px;font-family: 'ButlerSemiBold'"><%= @project&.year %><span class="etch"> | </span><i>Edition of <%= @project&.edition %></i><span class="etch"> | </span><i><%= @project&.dimensions %></i><span class="etch"> | </span><i><%= @project&.price %></i></p>
    <p style="text-align:center; padding-bottom: 20px;"></p>
  <% else %>
    <p style="text-align:center; padding-bottom: 20px;font-family: 'ButlerSemiBold'">
      <%= @project&.description %><span class="etch"> | </span><i><%= @project&.year %></i><span class="etch"> | </span><i><%= @project&.finish %></i></p>
    </p>
  <% end %>
  <% if @project.photos.length > 0 %>
    <div class="show-images" data-images='<%= @project.photos.reverse.map { |p| cl_image_path( p.url, :format => :jpeg, :quality => :auto) } %>' id="image-access">
      <div class="main-image text-center">
        <% if user_signed_in? && @project.photos.length > 0 %>
          <%= link_to photo_path(id:@project.photos[0], project:@project), :method => :delete do %>
            <p>&times;</p>
          <% end %>
        <% end %>
        <img src="<%= cl_image_path(@project.photos.order(created_at: :desc).first.url, :format => :jpeg) %>" alt="" id="main-image" class="new-image" data-toggle="modal" data-target="#myModal">
      </div>
      <div class="other-images">
        <div class="container text-center" style="width:100%">
          <div class="frow">
            <% @project.photos.order(created_at: :desc)[1..-1].each do |photo| %>
              <div class="image-card">
                <% if user_signed_in? %>
                  <%= link_to photo_path(id:photo, project:@project), :method => :delete do %>
                    <p>&times;</p>
                  <% end %>
                <% end %>
                <img src="<%= cl_image_path(photo.url, :format => :jpeg, :quality => 20) %>" class="additional-images" alt="Main Project Photo" data-toggle="modal" data-target="#myModal">
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>


  <% @project.photos.order(created_at: :desc).each do |photo| %>
    <div class="mobile-image">
      <img src="<%= cl_image_path(photo.url, :format => :jpeg, :quality => 20) %>" class="additional-images" alt="Main Project Photo" data-toggle="modal" data-target="#myModal">
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div class="hey-james">
      <p>Hey James, the below links are only visible to you</p>
      <% if current_user %>
        <div class="edit-delete-links">
          <%= link_to edit_project_path(@project) do %>
            <div class="edit links-circle">
              <%= image_tag 'weld.png', class: "links-icons" %>
            </div>
          <% end %>
          <%= link_to project_path(@project), method: :delete do %>
            <div class="delete links-circle">
              <%= image_tag 'bin.png', class: "links-icons" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%= cl_image_tag @project.photo, class: "bronze-image" %>

<% if @project.photos.length > 0 %>
  <div id="myModal" class="modal fade" role="dialog">
    <div data-dismiss="modal"><%= image_tag 'close.png', class: "close-modal-icon", id:"close-modal" %></div>
    <div class="modal-container">
      <div class="modal-image">
        <%= image_tag "back.png", id:"left-trigger" %>
        <%= cl_image_tag(@project.photos.first.url, :format => :jpeg, :quality => 20, :id=>"modal-image")%>
        <%= image_tag "next.png", id:"right-trigger" %>
      </div>
    </div>
  </div>
<% end %>

<script>
  const mainImage = document.getElementById("main-image")
  const smallImages = document.querySelectorAll('.additional-images')
  const mainStartingImage = mainImage.src
  const leftTrigger = document.getElementById("left-trigger")
  const rightTrigger = document.getElementById("right-trigger")
  const modalImage = document.getElementById("modal-image")
  let visibleImage = modalImage.src
  const initialImages = JSON.parse(document.getElementById("image-access").dataset.images)
  const images = []

  initialImages.forEach(function(image) {
    images.push(image.replace("q_auto", "q_20"))
  })

  let currentImage = images.indexOf(visibleImage)

  modalImage.addEventListener('click', function() {
    console.log(modalImage.src)
    modalImage.src = mainStartingImage.image.src
    console.log(modalImage.src)
  })

  smallImages.forEach(function(image) {
    image.addEventListener('mouseover', function() {
      mainImage.src = image.src
    });
    image.addEventListener('mouseout', function() {
      mainImage.src = mainStartingImage
    })
    image.addEventListener('click', function() {
      console.log(modalImage.src)
      modalImage.src = image.src
      console.log(modalImage.src)
    })
  });

  // On click this tests to see if the current image is the last image in the array, if it is then the carousel sets the modalImage source to the first image in the array, else it sets it to be the next element in the array

  rightTrigger.addEventListener('click', function() {
    if (currentImage === images.length-1) {
      modalImage.src = images[0]
      visibleImage = modalImage.src
      currentImage = images.indexOf(visibleImage)
    } else {
      modalImage.src = images[currentImage + 1]
      visibleImage = modalImage.src
      currentImage = images.indexOf(visibleImage)
    }
  })

  // Similarly, this tests to see if the current image is the first, if it is then the modalImage source is set to the last image in the array, ''.

  leftTrigger.addEventListener('click', function() {
    if (currentImage === 0) {
      modalImage.src = images[images.length-1]
      visibleImage = modalImage.src
      currentImage = images.indexOf(visibleImage)
    } else {
      modalImage.src = images[currentImage - 1]
      visibleImage = modalImage.src
      currentImage = images.indexOf(visibleImage)
    }
  })

  // Reset the modal to show the first image when the modal is closed

  // document.addEventListener("DOMNodeRemoved",function() {
  //   console.log("I am a bastard function")
  //   modalImage.src = images[0]
  //   visibleImage = modalImage.src
  //   currentImage = images.indexOf(visibleImage)
  // });
</script>

app/views/shared/_card.html.erb
<div class="card">
  <%= link_to project_path(project) do %>
    <div class="card-image" style="background-position:center;background-image: url(<%= project.photos.empty? ? image_path("Logo.jpg") : cl_image_path(project.photos.first.url, :format => :jpeg, :quality => :auto)%>);">
    </div>
    <h3 style="margin-top:10px;"><%= project.name %></h3>
    <% if current_user %>
      <div class="edit-delete-links">
        <%= link_to edit_project_path(project) do %>
          <div class="edit links-circle">
            <%= image_tag 'weld.png', class: "links-icons" %>
          </div>
        <% end %>
        <%= link_to project_path(project), method: "delete" do %>
          <div class="delete links-circle">
            <%= image_tag 'bin.png', class: "links-icons" %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <% if user_signed_in? %>
    <%= link_to "NEW PROJECT", new_project_path %>
    <%= link_to "NEW BLOG", new_update_path %>
    <%= link_to "Homepage", edit_homepage_path(Homepage.first) %>
  <% else %>
    <div class="footer-left">
      <p style="margin-bottom: 0px;">jamie1wild@gmail.com - +44 7921812332</p>
    </div>
  <% end %>
  <div class="footer-center">
    <%= link_to "https://www.instagram.com/james_wild_sculptures/", class: "insta-link", target: "_blank" do %>
      <i class="fab fa-instagram footer-insta"></i>
    <% end %>
  </div>
  <div class="footer-right">
    <p style="margin-bottom: 0px;">Built by Hoxton Digital <a href="https://www.hoxton-digital.com/" style="display: none;">London Web Development</a></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% unanswered = Contact.where(sent: false) %>
<div class="navbar-JW">
  <div class="navbar-left">
    <%= link_to "/", class: "log-a" do %>
      <h3 class="logo-link">JAMES WILD</h3>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link-dark" do %>
        <i class="fas fa-sign-out-alt" style="margin-left: 20px;"></i>
      <% end %>
    <% end %>
  </div>
  <div class="navbar-right">
    <% if action_name == "bronze" %>
      <div class="active-link">
        <%= link_to "BRONZE", bronze_path, class:"no-margin navbar-link"%>
      </div>
    <% else %>
      <div class="inactive-link">
        <%= link_to "BRONZE", bronze_path, class:"no-margin navbar-link"%>
      </div>
    <% end %>
    <% if action_name == "scrap" %>
      <div class="active-link">
        <%= link_to "SCRAP", scrap_path, class:"no-margin navbar-link"%>
      </div>
    <% else %>
      <div class="inactive-link">
        <%= link_to "SCRAP", scrap_path, class:"no-margin navbar-link"%>
      </div>
    <% end %>
    <% if action_name == 'about' %>
      <div class="active-link">
        <%= link_to "ABOUT", about_path, class:"no-margin navbar-link"%>
      </div>
    <% else %>
      <div class="inactive-link">
        <%= link_to "ABOUT", about_path, class:"no-margin navbar-link"%>
      </div>
    <% end %>
    <% if controller_name == "updates" && action_name == 'index' %>
      <div class="active-link">
        <%= link_to "NEWS", news_path, class:"no-margin navbar-link"%>
      </div>
    <% else %>
      <div class="inactive-link">
        <%= link_to "NEWS", news_path, class:"no-margin navbar-link"%>
      </div>
    <% end %>
    <% if action_name == "new" %>
      <div class="active-link">
        <%= link_to "CONTACT", new_contact_path, class:"no-margin navbar-link"%>
      </div>
    <% else %>
      <div class="inactive-link">
        <%= link_to "CONTACT", new_contact_path, class:"no-margin navbar-link"%>
      </div>
    <% end %>
  </div>
</div>


<div class="mobile-nav">
  <div class="mobile-navbar-left">
    <%= link_to "/", class: "log-a" do %>
      <h3 class="logo-link">JAMES WILD</h3>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link-dark" do %>
        <i class="fas fa-sign-out-alt" style="margin-left: 20px;"></i>
      <% end %>
    <% end %>
  </div>
  <div class="mobile-navbar-right">
    <div class="dropdown">
      <img style="height: 30px; width: 30px; margin-right: 10px;" src="<%= image_path('menu.png') %>" alt="Hamburger" id="dropdownMenuButton">
      <div class="drop-menu" id="drop-menu">
        <%= link_to "BRONZE", bronze_path, class:"vert-margin navbar-link"%>
        <%= link_to "SCRAP", scrap_path, class:"vert-margin navbar-link"%>
        <%= link_to "ABOUT", about_path, class:"vert-margin navbar-link"%>
        <%= link_to "NEWS", news_path, class:"vert-margin navbar-link"%>
        <%= link_to "CONTACT", new_contact_path, class:"vert-margin navbar-link"%>
        <% if current_user %>
          <%= link_to "MAILING", contacts_path, class:"vert-margin navbar-link"%>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
  var menu = document.getElementById('drop-menu')
  document.getElementById('dropdownMenuButton').addEventListener("click", () => {
    menu.classList.toggle("show");
    console.log('clicked')
  })
</script>

app/views/updates/index.html.erb
<div class="bg" style="background-image: url(<%= asset_path(@bg) %>);">
  <div class="container" style="padding: 0 5vw;">
    <div class="main-text" style="margin-top: 0px;">
      <h3 class="index-header mb40">NEWS FROM THE WORKSHOP</h3>
    </div>
    <div class="row">
      <% @updates.each do |update| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= link_to update_path(update) do %>
            <div class="latest-work-card update" style="background-image: url(<%= update.photo? ? cl_image_path(update.photo, :format => :webp, :quality => 10) : image_path("Logo.jpg") %>);">
              <div class="latest-work-title small"><%= update.title.truncate(60) %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/updates/show.html.erb
<div class="bg" style="background-image: url(<%= asset_path(@bg) %>);">
  <div class="container"  style="padding: 0 5vw;">
    <div class="main-text" style="margin-top: 0px;">
      <h3 class="index-header mb40"><%= @update.title %></h3>
    </div>
    <p class="pb etch"><strong>Posted: <%= @update.created_at.strftime("%d/%m/%Y") %></strong></p>
    <%= cl_image_tag @update.photo, class: "bronze-image" %>
    <div class="dcen">
      <div style="margin-top: 50px;">
        <p class="text-center pb" style="width: 100%;text-align: justify;"><%= @update.description%></p>
      </div>
    </div>
    <% if @update.link.present? %>
      <div>
        <a href="<%= @update.url %>"><%= @update.link %></a>
      </div>
    <% end %>
    <%= @update.content %>
    <% if current_user %>
      <%= link_to "EDIT", edit_update_path(@update) %>
      <%= link_to "DELETE", update_path(@update), method: :delete %>
    <% end %>
  </div>
</div>